version: "3.8"

#Docker Networks
networks:
    laravel:
        driver: bridge

#Volumes
volumes:
    db_data:
        driver: local

# Workflow
services:
    # MYSQL
    mysql:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_HOST: ${DB_HOST}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - db_data:/var/lib/mysql/
        networks:
            - laravel

    # phpmyadmin
    phpmyadmin:
        image: phpmyadmin:latest
        container_name: phpmyadmin
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: always
        depends_on:
            - mysql
        ports:
            - "8081:80"
        volumes:
            - /sessions
        networks:
            - laravel
        links:
            - mysql
